spring:
  
  messages:
    encoding: UTF-8
    basename: i18n/messages,i18n/common-messages
    compression:
      request:
        enabled: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
      response:
        enabled: true
