data:
  env: chat-cloud-base-config-server-dev1111
  user:
    username: username-chat-cloud-base-config-server-dev
    password: password-chat-cloud-base-config-server-dev
  service:
    ids: chat-cloud-provider-user;chat-cloud-base-config-server1
